rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - rbx
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_success: change # only send if status changes
